<a href="https://colab.research.google.com/github/yasna21/MNIST-DigitClassification-/blob/main/exploring_nyc_public_school_test_result_scores.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# import libraries
import pandas as pd
import numpy as np
from scipy import stats


# Read in the data
schools = pd.read_csv("/content/drive/MyDrive/schools.csv")

# Preview the data
schools.head()

# Create a DataFrame which Contains school_name and average_math columns.
best_math_schools = schools[schools['average_math'] >= 640][['school_name', 'average_math']].sort_values('average_math', ascending=False)
best_math_schools.head()

# Calculate total SAT
schools['total_SAT'] = schools['average_math'] + schools['average_reading'] + schools['average_writing']
schools.head()

,school_name,borough,building_code,average_math,average_reading,average_writing,percent_tested,total_SAT
0,"New Explorations into Science, Technology and ...",Manhattan,M022,657,601,601,NaN,1859
1,Essex Street Academy,Manhattan,M445,395,411,387,78.9,1193
2,Lower Manhattan Arts Academy,Manhattan,M445,418,428,415,65.1,1261
3,High School for Dual Language and Asian Studies,Manhattan,M445,613,453,463,95.9,1529
4,Henry Street School for International Studies,Manhattan,M056,410,406,381,59.7,1197

In [ ]:
# Top 10 performing schools
top_10_schools = schools[['school_name','total_SAT']].sort_values('total_SAT', ascending=False).head(10)

In [ ]:
# NYC borough with highest sdt.
boroughs = schools.groupby('borough')['total_SAT'].agg(['count', 'std', 'mean']).round(2)
largest_std_dev = boroughs[boroughs['std'] == boroughs['std'].max()]
largest_std_dev = largest_std_dev.rename(columns={'count': 'num_schools', 'mean':'average_SAT', 'std':'std_SAT'})
largest_std_dev.reset_index(inplace=True)